version: '3'

services:
  node:
    # the name of our contianer 
    container_name: 'worker_node'
    # base image of node take 12 now
    image: node:${NODE_VERSION}
    #invoke our shell script into the contianer 
    command: "sh dev-local/dev-entrypoint.sh"
    # command: [ "/bin/sh", "-c", "--", "while true; do sleep 30; done;" ]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    environment:
      # set no proxy in case you need for example kafka
      NO_PROXY: "kafka1"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    ports:
      - "9229:9229" # debug port
      - "9329:9329" # debug port
    # logging:
    #   driver: none # Disable the log to console

volumes:
  node-modules:
